// src/app/layout.tsx
import type { Metadata } from "next";
import localFont from "next/font/local";
import Sidebar from "./components/Sidebar"; // Import Sidebar
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="grid grid-cols-[auto,1fr] h-screen">
          <Sidebar /> {/* Sidebar */}
          <main className="p-4 overflow-auto">
            {/* Static content for testing */}
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
